<?xml version="1.0" encoding="UTF-8"?><testrun name="DefaultRunner (2)" project="Savynt" tests="2" started="2" failures="0" errors="1" ignored="0">
  <testsuite name="Runner.DefaultRunner" time="55.001">
    <testsuite name="Feature: Access for Dev3" time="19.328">
      <testcase name="user get access for DEV 3" classname="Access for Dev3" time="19.328"/>
    </testsuite>
    <testsuite name="Feature: Savynt Access" time="35.673">
      <testcase name="LOA3 and No MFA" classname="Savynt Access" time="35.673">
        <error>java.lang.IndexOutOfBoundsException: Index: 15, Size: 15&#13;
	at java.util.ArrayList.rangeCheck(Unknown Source)&#13;
	at java.util.ArrayList.get(Unknown Source)&#13;
	at Steps.GUIStepDefination.user_gave_NO_MFA_Access(GUIStepDefination.java:64)&#13;
	at âœ½.user gave NO MFA Access(file:src/test/resources/Features/SavyntAccess.feature:6)&#13;
&#13;
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testrun>
